### ISSUE TITLE
DateColumn does not accepts 'null'

### ISSUE THREAD

**Issue by patrickkusebauch** [mesour/DataGrid#30]
Instead it creates new instance of Datetime with current date and time. If the source does not provide date for the column (for example something has not yet happened), the datagrid automatically assumes current date.

**Comment by michalfibek** [comment]
+ 1, found this bug right now

**Comment by mesour** [comment]
Fixnuto. Pokud je datum nulový, tak zobrazí pomlčku. Při editable se vymaže, aby nevznikl konflikt s datepickerem.
