### ISSUE TITLE
Doctrine Source Doesn't Include Associations

### ISSUE THREAD

**Issue by oddz** [mesour/DataGrid#54]
The doctrine source doesn't recure through associations when converting entities to flat arrays. This results in any of those columns not being compatible with ordering and filtering. The fix is to have the conversion process in the source not only check for fields but associations as well and include them recursively.

**Comment by oddz** [comment]
This method is the culprit.

Mesour\Source\DoctrineSource::getEntityArrayAsArrays

**Comment by mesour** [comment]
I think I'm doing on the entity an obligation to have a method toArray and method Mesour\Source\DoctrineSource::getEntityArrayAsArrays can be removed

**Comment by oddz** [comment]
That is an option but it would be nice to have the data source take care of that logic.

**Comment by mesour** [comment]
Oh you mean this :) Can use second parameter of `DoctrineGridSource::__construct($queryBuilder, array $columnMapping)`.

Example column mapping:

```php
$columnMapping = [
    'id' => 'user.id',
    'group_name' => 'group.name',
];
$source = new DoctrineGridSource($queryBuilder, $columnMapping);
```

**Comment by mesour** [comment]
For problem with getEntityArrayAsArrays can use fast fix for now:

```php
class GridSource extends DoctrineGridSource
{
	protected function getEntityArrayAsArrays($results)
	{
		$output = [];
		foreach ($results as $result) {
			if (method_exists($result, 'toArray')) {
				$output[] = $result->toArray();
			} else {
				throw new InvalidArgumentException('Entiti must have method toArray().');
			}
		}
		return $output;
	}
}
```

**Comment by mesour** [comment]
Issue moved to [mesour/sources #10](https://github.com/mesour/sources/issues/10) via [**ZenHub.io**](https://www.zenhub.io/)
